const pro = [
  {
    id: 1,
    img: "images/bike.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 0,
    location: "online",
  },
  {
    id: 2,
    img: "images/wedding.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 1,
    location: "online",
  },
  {
    id: 3,
    img: "images/image 12.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 1,
    location: "offline",
  },
  {
    id: 4,
    img: "images/image 22.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 0,
    location: "online",
  },
  {
    id: 5,
    img: "images/image 23.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 0,
    location: "offline",
  },
  {
    id: 6,
    img: "images/image 24.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 0,
    location: "offline",
  },
  {
    id: 7,
    img: "images/image 25.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 1,
    location: "offline",
  },
  {
    id: 8,
    img: "images/image 26.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 1,
    location: "online",
  },
  {
    id: 9,
    img: "images/image 27.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 0,
    location: "online",
  },
  {
    id: 10,
    img: "images/image 28.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 1,
    location: "online",
  },
  {
    id: 11,
    img: "images/image 29.png",
    rate: "5.0",
    country: "USA",
    des: "Life lessons with Katie Zaferes",
    salary: 125,
    soldout: 0,
    location: "offline",
  },
];
export default pro;
